version: 2


aliases:
  - &defaults
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk
  - &release_filter
    filters:
      tags:
        only: /.*/
      branches:
        ignore: /.*/
  - &master_filter
    filters:
      branches:
        only: master

jobs:

  build_daemon_and_cli:
    working_directory: ~/cyberd
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build And Test Project
          command: |
            export GO111MODULE=on
            go build -o cyberd ./daemon
            go build -o cyberdcli ./cli
            go build -o cyberdproxy ./proxy


  update_changelog:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - checkout
      - run:
          name: Update Changelog
          command: |
            cid=$(docker run -d -it ferrarimarco/github-changelog-generator:1.14.3 -u cybercongress -p cyberd --exclude-tags-regex .*[.].*[.].*[.].* --token $CHANGELOG_GITHUB_TOKEN )
            docker attach $cid
            docker cp $cid:/usr/local/src/your-app/CHANGELOG.md ./CHANGELOG.md
            diff=$(git diff CHANGELOG.md)
            if [[  -n  "$diff" ]]; then
              git config --global user.email "cybercongress42@gmail.com"
              git config --global user.name "Cyber Admin"
              git add CHANGELOG.md
              git commit -m "Circle CI: Update Changelog"
              git push --set-upstream origin master
            fi


  update_docs:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update Docs
          working_directory: ~/workdir
          command: |
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/library.git
      - deploy:
          name: Update docs from cyberd repo
          working_directory: ~/workdir/library
          command: |
            # We need to remove current files in folder to avoid duplicating renamed files
            rm -rf ./wiki/docs/cyberd/*
            cp -r ~/build/docs/. ./wiki/docs/cyberd/
            cp ~/build/CHANGELOG.md ./wiki/docs/cyberd/Changelog.md
            cp ~/build/CONTRIBUTING.md ./wiki/docs/cyberd/Contributing.md
            cp ~/build/ROADMAP.md ./wiki/docs/cyberd/Roadmap.md
            git add -N wiki/docs/cyberd
            diff=$(git diff wiki/docs/cyberd/)
            if [[  -n  "$diff" ]]; then
              git config user.email "cybercongress42@gmail.com"
              git config user.name "Cyber Admin"
              git add wiki/docs/cyberd/
              git commit -m "Circle CI: Update Docs"
              # Push quietly to prevent showing the token in log
              git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/library.git master
            fi


  build_and_deploy_images_to_dockerhub:
    working_directory: ~/cyberd
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build And Deploy Cyberd Image
          command: |
            docker build -t build/cyberd .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag build/cyberd cyberd/cyberd:$CIRCLE_TAG
            docker push cyberd/cyberd:$CIRCLE_TAG


  release_cyberdcli_binaries:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/cybercongress/cyberd
    steps:
      - checkout
      - run:
          name: Github Release Cyberd Binaries
          command: |
            export GO111MODULE=on
            go build -o cyberdcli ./cli
            sudo apt-get update && sudo apt-get install -y rpm
            curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  cyberd_build:
    jobs:
      - build_daemon_and_cli:
          filters:
            tags:
              only: /.*/
      - update_changelog:
          <<: *master_filter
          requires:
            - build_daemon_and_cli
      - update_docs:
          <<: *master_filter
          requires:
            - build_daemon_and_cli
      - build_and_deploy_images_to_dockerhub:
          <<: *release_filter
          requires:
            - build_daemon_and_cli
      - release_cyberdcli_binaries:
          <<: *release_filter
          requires:
            - build_daemon_and_cli
